function(copy_file file_path destination)
	get_filename_component(DEST_DIR "${destination}" DIRECTORY)
	get_filename_component(DEST_NAME "${destination}" NAME)
	get_filename_component(FILE_DIR "${file_path}" DIRECTORY)
	get_filename_component(FILE_NAME "${file_path}" NAME)

	if (EXISTS "${file_path}")
		if (NOT EXISTS "${DEST_DIR}")
			file(MAKE_DIRECTORY "${DEST_DIR}")
		endif (NOT EXISTS "${DEST_DIR}")

		file(COPY "${FILE_DIR}/${FILE_NAME}" DESTINATION "${DEST_DIR}")
        file(RENAME "${DEST_DIR}/${FILE_NAME}" "${DEST_DIR}/${DEST_NAME}")
    else (EXISTS "${file_path}")
        message(WARNING "Failed to copy \"${file_path}\": file does not exist.")
    endif (EXISTS "${file_path}")
endfunction(copy_file file_path destination)

function(copy_directory_contents directory destination)
	if (EXISTS "${directory}" AND IS_DIRECTORY "${directory}")
		file(GLOB FILES "${directory}/*")

		foreach(FILE ${FILES})
			# get_filename_component(FILENAME "${FILE}" NAME)
			# message(STATUS "Copying file \"${FILE}\" -> \"${destination}/${FILENAME}\".")
			file(COPY "${FILE}" DESTINATION "${destination}")
		endforeach(FILE)
	else (EXISTS "${directory}" AND IS_DIRECTORY "${directory}")
		message(WARNING "Failed to copy directory contents from \"${directory}\": path does not exist or is not a directory.")
	endif (EXISTS "${directory}" AND IS_DIRECTORY "${directory}")
endfunction(copy_directory_contents directory destination)
